site_name: 'docs'


# Output to this director
site_dir: techdocs/
# Input director
docs_dir: developer-docs
repo_url: https://github.com/tokens-studio/token-studio-sdk/
# Should have the same value as the docs-dir
edit_uri: edit/-/developer-docs/
theme:
    name: readthedocs

plugins:
    - techdocs-core
