site_name: 'docs'

nav:
  - Home: index.md

docs_dir: developer-docs
repo_url: https://github.com/tokens-studio/token-studio-sdk/
edit_uri: edit/-/docs/
theme:
    name: readthedocs

plugins:
  - techdocs-core