name: Pull Request

on: pull_request

jobs:
    verify:
        name: Verify changes
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test
              env: # Or as an environment variable
                  TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
                  TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
                  TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
                  TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
